### ISSUE TITLE
Feature: add main content filters

### ISSUE THREAD

**Issue by yuvalbl** [hasadna/anyway-newsflash-infographics#10]
![image](https://user-images.githubusercontent.com/11487010/71589395-623e6380-2b2d-11ea-85f2-a145d9309bf7.png)
Filter should behave as a dropdown list with the following values:

- 1 year
- 3 years
- 5 years
- 8 years

At this stage not action required on selection

**Comment by noamgor** [comment]
need premession to open new branch to push :)

**Comment by yuvalbl** [comment]
Now you have it, Sorry for the delay :smile_cat:

**Comment by noamgor** [comment]
[https://github.com/hasadna/anyway-newsflash-infographics/pull/30](url)
