### ISSUE TITLE
[Bug] leaflet map render problem in side bar  

### ISSUE THREAD

**Issue by citizen-dror** [hasadna/anyway-newsflash-infographics#106]
in SideBar LocationMap ,
a tile don't load on first render :
![image](https://user-images.githubusercontent.com/342644/78037933-db3f9800-7374-11ea-887e-62832dd4a407.png)

```
  <Box flexBasis={300} flexShrink={0} p={1}>
      <LocationMap data={[{latitude: 32.0853, longitude: 34.7818}]} center={{lat: 32.0853, lng: 34.7818}}/>
      </Box>
```

1 - can fix it with change in css of container   (copied form AnyWayCard)
```
  const cardStyles: object = {
    padding: '10px',
    margin: '10px',
    width: '300px',
    height: '350px',
    display: 'flex',
    justifyContent: 'space-evenly',
    flexDirection: 'column'
  }
...

    <Box style={cardStyles}>
      <LocationMap data={[{latitude: 32.0853, longitude: 34.7818}]} center={{lat: 32.0853, lng: 34.7818}}/>
      </Box>
```
![image](https://user-images.githubusercontent.com/342644/78038632-b7308680-7375-11ea-8fab-96de74d5373a.png)

2- need to adjust the css. 

3- in case of resize - maybe need to use 
mapRef.current.leafletElement.invalidateSize(false);

**Comment by yuvalbl** [comment]
@danielsh28 please see if you can reconstruct, if not - close it

**Comment by danielsh28** [comment]
the bug not  reproduced, apparently after  switching to google maps tile layer
