### ISSUE TITLE
Change WidgetType to enum

### ISSUE THREAD

**Issue by mimafogeus2** [hasadna/anyway-newsflash-infographics#15]
`WidgetType` would work better as an enum with textual values.

**Comment by yuvalbl** [comment]
@mimafogeus2 is this issue still relevant?

**Comment by citizen-dror** [comment]
i'm not sure wat to do here..

somthing like ..?

export enum IWidgetTypes{
  IWidgetMostSevereAccidents,
  IWidgetAccidentsHeatMap,  
  IWidgetAccidentsByDayNight, 
  IWidgetCountBySeverity, 
  IWidgetAccidentsByType,
  IWidgetInjuredByYear,  
  IWidgetAccidentsByYear
}

**Comment by yuvalbl** [comment]
solved
