### ISSUE TITLE
feature: add footer

### ISSUE THREAD

**Issue by yuvalbl** [hasadna/anyway-newsflash-infographics#18]
add footer
click on **Hasadna** logo should go to [hasadna home page](https://www.hasadna.org.il/) 
![image.png](https://images.zenhubusercontent.com/59ec85baa468affe6df7a947/b7f35392-61a2-4a18-9231-ec2cc074a690)

Use [Anyway](https://anyway.co.il/) site as a reference. **no need** to add facebook / twitter buttons / icons

**Comment by citizen-dror** [comment]
already merged
