### ISSUE TITLE
[Bug]-issues with text in most severe accidents widget PNG

### ISSUE THREAD

**Issue by yaeluria** [hasadna/anyway-newsflash-infographics#233]
**To Reproduce**
Download the png for most severe accidents table widget. The text in the downloaded png has issues with spacing between words and text direction. At least on macOs.

**Expected behavior**
PNG should match original widget on the app.

**Screenshots**
![Screen Shot 2020-05-13 at 8 03 00 PM](https://user-images.githubusercontent.com/37266719/81846728-390df500-955b-11ea-8758-667d194b1df3.png)

**Comment by yuvalbl** [comment]
fix by #259
Not supported by Safari

**Comment by yaeluria** [comment]
Looks fine on safari. There are bugs in some of the other widgets that I will open issues for.
