### ISSUE TITLE
Add non technical documentation about project's vision

### ISSUE THREAD

**Issue by yuvalbl** [hasadna/anyway-newsflash-infographics#25]
1.  At the root directory, Add file named Vision.MD
2. Write an overview about the project's vision using [markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet). Include links and resources which explain the anyway and vision zero.

Keep in mind: **The Goal** here is to **help new contributors** to understand the project and it needs. It should provide **a good replacement to ***AnyWay*** introduction talk** in case a project leader is not around to give one.

**Comment by citizen-dror** [comment]
already merged
