### ISSUE TITLE
doc: improve README.md

### ISSUE THREAD

**Issue by yuvalbl** [hasadna/anyway-newsflash-infographics#26]
Improve README.md
add link to Diving in section:

- [documentation](https://github.com/hasadna/anyway-newsflash-infographics/issues?q=is%3Aopen+is%3Aissue+label%3Adocumentation)

- [good first issue](https://github.com/hasadna/anyway-newsflash-infographics/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)

Report for any other missing links in README.md

**Comment by mimafogeus2** [comment]
Done :)
