### ISSUE TITLE
[Bug] News content should always take the entire container space

### ISSUE THREAD

**Issue by yuvalbl** [hasadna/anyway-newsflash-infographics#264]
**Describe the bug**
When there are few or no newsflashes, news area shrink
This is mostly obvious when change filter from one with no results to one with results

**To Reproduce**
1. Go to homepage
2. Click on "Mada" filter button
3. Wait for items load -  you'll see no items found
4. Click on "All" filter button

**Expected behavior**
Loader should still expand to the entire newsflash conatiner

**Screenshots**
This is OK:
![image](https://user-images.githubusercontent.com/11487010/82583961-79452700-9b9c-11ea-9527-23c94dbda5c6.png)

This is NOT OK:
![image](https://user-images.githubusercontent.com/11487010/82583893-63376680-9b9c-11ea-96e6-d145f6716013.png)

**Environment**
Browser: Chrome

**Additional context**
The problem is probably with the newsflash containing element
The overlay loader always take the size of it's container

Also when loading and scrolling down:
![image](https://user-images.githubusercontent.com/11487010/83033558-edba1300-a03f-11ea-82d1-03c50732545c.png)

**Comment by yuvalbl** [comment]
@Meital-Lazarovich 
Can we reconstruct this?

**Comment by 9Syncopation** [comment]
cannot reconstruct
