### ISSUE TITLE
[Bug] on Safari most severe accidents widgets is empty with error text

### ISSUE THREAD

**Issue by yaeluria** [hasadna/anyway-newsflash-infographics#275]
**Describe the bug**
The most severe accidents widgets is empty and has error text "Invalid Component widget"

**To Reproduce**
2. Scroll down to the most severe accidents widgets (the third one)

**Expected behavior**
Should appear as it does on chrome.

**Screenshots**
![Screen Shot 2020-05-27 at 8 06 16 PM](https://user-images.githubusercontent.com/37266719/83054693-7abe9580-a05b-11ea-9e23-86b064746f9b.png)

**Environment**
Browser: Safari
Environment: Local and Production

**Comment by almogbhl** [comment]
https://github.com/hasadna/anyway-newsflash-infographics/pull/451

**Comment by almogbhl** [comment]
solved
