### ISSUE TITLE
[Feat] Implement getVerifiedWidgetsData

### ISSUE THREAD

**Issue by yuvalbl** [hasadna/anyway-newsflash-infographics#317]
Add checks per widget-data object

1. move getVerifiedWidgetsData to a seperate service file `data-verification.service.ts`
2. make sure validation will not pass for invalid data
For example, see head-on collision widget for the following newsflash: 
https://anyway-newsflash-infographics.web.app/newsflash/47316

see `getVerifiedWidgetsData`
```
    // TODO
    // add checks per widget (switch) here
    isValid = isValid && perWidgetFn()
```

**Comment by SejoB** [comment]
done by #691
