### ISSUE TITLE
[Bug] Thank you / About Modal - X is in the wrong position

### ISSUE THREAD

**Issue by yuvalbl** [hasadna/anyway-newsflash-infographics#325]
Thank you / About Modal - X is in the wrong position

**To Reproduce**
1. Click on  Thank you / About link in the footer

**Expected behavior**
X should be positioned closer to the left edge 

**Screenshots**
![image.png](https://images.zenhubusercontent.com/59ec85baa468affe6df7a947/a8040055-0779-4b23-92a9-d12e4a6b5939)

**Environment**
Browser: Chrome

**Comment by ronfybish** [comment]
@yuvalbl 
The problem is that the AnywayAppBar component is with left and right padding by default....
So, to fix that bug we need to edit the appbar component or to find another solution.

![1](https://user-images.githubusercontent.com/41908747/90425831-0ed35280-e0c9-11ea-9c91-3e311c907bcd.JPG)

**Comment by yuvalbl** [comment]
Duplication of #431
