### ISSUE TITLE
[Feat] Add change language button

### ISSUE THREAD

**Issue by yuvalbl** [hasadna/anyway-newsflash-infographics#330]
Add change language button - for hebrew / english  / arabic
Steps:
- [x] Create language buttons
- [ ] Connect click event to store event - "changeLanguage"
- [ ] On changeLanguage event 1  - change static translation  
- [ ] On changeLanguage event 2 - fetch data with the selected locale (TBD)  

resources:
https://react.i18next.com/legacy-v9/step-by-step-guide
https://www.i18next.com/overview/api#changelanguage

Blocked by #328

**Comment by yaeluria** [comment]
This is continued on #371 with a different approach
