### ISSUE TITLE
[Bug] Map are invisible on staging

### ISSUE THREAD

**Issue by yuvalbl** [hasadna/anyway-newsflash-infographics#332]
**Map are invisible on staging**

**To Reproduce**
1. Go to https://anyway-newsflash-infographics.web.app/

**Expected behavior**
Map should be displayed properly

![image.png](https://images.zenhubusercontent.com/59ec85baa468affe6df7a947/5b366724-76d6-4a89-aeab-e22372f68d2c)

**Comment by 9Syncopation** [comment]
while checking at my local machine the maps are visible.
both at localhost & web app (https://anyway-newsflash-infographics.web.app/)
tested the behavior at chrome, Firefox & Microsoft edge- all are visible
localhost >>>
![image](https://user-images.githubusercontent.com/50585461/86542694-99e4f880-bf20-11ea-8c40-e0fd4cf6693d.png)

web app >>>
![image](https://user-images.githubusercontent.com/50585461/86542717-b84af400-bf20-11ea-92bd-9fd22363388d.png)

**Comment by yuvalbl** [comment]
Thanks @9Syncopation 
I cannot reconstruct that now, maybe have something to do with chrome extension I've been using.
Closing this issue
