### ISSUE TITLE
Add Most Severe Accidents widget (map)

### ISSUE THREAD

**Issue by mimafogeus2** [hasadna/anyway-newsflash-infographics#37]
Add a widget that receives an array of data in the format:

```
{
  "longitude": 34.9780568296871,
  "latitude": 32.4543458814189,
  "accident_severity": "קשה",
  "accident_timestamp": "2016-05-15 21:00:00"
}
```

And shows it on a map.

There's a location widget component that you can use for this, but it might need modification to work with multiple locations.

**Comment by yuvalbl** [comment]
solved by #92
