### ISSUE TITLE
[Bug] The cursor for the footer tabs should be pointer

### ISSUE THREAD

**Issue by ronfybish** [hasadna/anyway-newsflash-infographics#379]
**Describe the bug**
When hovering on the footer Tabs ("About"/"Thanks") the cursor should be "pointer" and currently it "text"  

**To Reproduce**
![WhatsApp Image 2020-08-17 at 19 50 31](https://user-images.githubusercontent.com/41908747/90422512-a46be380-e0c3-11ea-9e6d-9982afe5f793.jpeg)
1. Go to Footer 
2. change style setting for cursor

**Expected behavior**
when hovering on the tabs the cursor needs to be "pointer"
![WhatsApp Image 2020-08-17 at 19 54 50](https://user-images.githubusercontent.com/41908747/90422751-f90f5e80-e0c3-11ea-85bf-fb7ae0dbe3d6.jpeg)

**Comment by yuvalbl** [comment]
solved
