### ISSUE TITLE
[Refactor] create one flexible bar chart view for different views

### ISSUE THREAD

**Issue by ronfybish** [hasadna/anyway-newsflash-infographics#387]
As the project grows the need for different representations of information in a bar chart grows. 
In order to deal with it effectively, it is important to re-build the BarChartView component that can display data as per our requirement for each widget.

For example

![2](https://user-images.githubusercontent.com/41908747/91041749-3a9a8f00-e619-11ea-9039-3aa29ab4cbdb.JPG)
![3](https://user-images.githubusercontent.com/41908747/91041753-3b332580-e619-11ea-99b3-e49561eb3ae6.JPG)
![1](https://user-images.githubusercontent.com/41908747/91041755-3bcbbc00-e619-11ea-9840-1aa615cb46e4.JPG)

The BarChartView should handle multiple options display has a single flexible componnent

**Comment by SejoB** [comment]
not relevant
