### ISSUE TITLE
[Refactor] Implement new design for textView

### ISSUE THREAD

**Issue by SejoB** [hasadna/anyway-newsflash-infographics#398]
-redesign textView widget that will match following design
-for now don't pay attention to sizes, fonts, etc.
-temporary logo can stay on bottom of Card
![image (3)](https://user-images.githubusercontent.com/39242962/92922988-61d9c480-f43f-11ea-9bb8-f951e90967c8.png)

**Comment by yaeluria** [comment]
continued on #414
