### ISSUE TITLE
[Bug] Newsflash 49203 show errors on console

### ISSUE THREAD

**Issue by yuvalbl** [hasadna/anyway-newsflash-infographics#404]
**Describe the bug**
Loading newsflash 49203 show errors on console:
* Multiple loading error: `You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors.`
* Several map-related  errors, like: `Uncaught TypeError: Cannot read property 'prototype' of undefined`

**To Reproduce**

1. Go to https://anyway-newsflash-infographics.web.app/newsflash/49203
2. See console

**Expected behavior**
No console error

**Screenshots**
![image](https://user-images.githubusercontent.com/11487010/93318410-54458580-f817-11ea-8aa7-34a47974c426.png)

**Environment**
Browser: Chrome 
Environment: Staging

**Additional context**
1. We should add a better map-component data validation and error catching.
2. It might be a data-related issue. If data is not valid - it should not pass `getVerifiedWidgetsData` function. See #317 for more details

**Comment by SejoB** [comment]
resolved after map fixing
