### ISSUE TITLE
[Bug] Compare by vehicle type - remove factional part

### ISSUE THREAD

**Issue by yuvalbl** [hasadna/anyway-newsflash-infographics#422]
**Describe the bug**
bar values have factional part

**To Reproduce**
See Compare by vehicle type. see bar values have factional part (see image below)

**Expected behavior**
Round value, so no fractional part presented. For example:
```
72.333333 // should be rounded to 72
72.6111   // should be rounded to 73
72.6      // should be rounded to 73
```  

**Screenshots**
![image](https://user-images.githubusercontent.com/11487010/95672437-7679bb80-0ba9-11eb-9898-afe3aa08a54d.png)

**Environment**
Browser: Chrome.
Environment: Staging.

**Comment by almogbhl** [comment]
done
