### ISSUE TITLE
[Refactor] Typography

### ISSUE THREAD

**Issue by yaeluria** [hasadna/anyway-newsflash-infographics#423]
The text view component currently makes use of two types of Text elements: WIDGET_TITLE and WIDGET_CONTENT, but there are additional font sizes in Box elements inside the Text element. Also, including a Box (which is essentially a div) inside a Text element which is usually a heading or a paragraph goes against HTML semantics (see console warning in the comment in PR #418).

Steps to solve: 
1. Define appropriate font sizes for the Text types (or use/ define other Text types) in Text.tsx
2. Use the Text types in the TextView component
3. Wrap only the text itself in Text elements (or at least no divs)

**Comment by yuvalbl** [comment]
Update: I've change this issue to address typography in general.
Steps:

1. create new typography elements (Done, see branch reafctor-423-typography)
2. replace theme typography options (see below)
3. Replace all `Text` elements with the new version of `Typography` elements - see Typography section in GUIDELINES.md
note that text does not have to be exactly as before, just make sure it looks nice

Material ui theme - typography overrides
```
typography: {
    fontFamily: fontFamilyString,
    // title variants (like: card headers)
    body1: {
      fontSize: 24,
      fontWeight: 700,
    },
    body2: {
      fontSize: 22,
      fontWeight: 700,
    },
    // body variants (like: newsflash data, widget contents etc)
    h1: {
      fontSize: 20,
      fontWeight: 700,
    },
    h2: {
      fontSize: 18,
      fontWeight: 700,
    },
    h3: {
      fontSize: 16,
      fontWeight: 700,
    },
    h4: {
      fontSize: 15,
      fontWeight: 700,
    },
    h5: {
      fontSize: 14,
      fontWeight: 700,
    },
    h6: {
      fontSize: 13,
    },
  },
```
