### ISSUE TITLE
[Bug] Dialog Issues

### ISSUE THREAD

**Issue by Meital-Lazarovich** [hasadna/anyway-newsflash-infographics#431]
**Describe the bug**
1. Unnecessary padding on the sides of the dialog
2. Link should be opened in a new page and not on top of the app. 

**To Reproduce**
Go to 'about' dialog

**Expected behavior**
Padding is aligned equally inside the dialog. Clicking the link is leading to a new tab with it's content.  

**Screenshots**
![image](https://user-images.githubusercontent.com/56398111/96131242-9be82b80-0f01-11eb-8c49-fb75f4c37930.png)

**Environment**
Browser: Chrome
Environment: Local

**Comment by daniel-ilan** [comment]
This is related and closed in #663
