### ISSUE TITLE
[Bug] Text view - direction on years rang is wrong in hebrew

### ISSUE THREAD

**Issue by c881** [hasadna/anyway-newsflash-infographics#436]
**Describe the bug**
Numbers in hebrew sentence should be written from right to left.
משעה/ שנה עד שעה/ שנה.

**Screenshots**
![IMG_20201020_090856.jpg](https://user-images.githubusercontent.com/2761537/96552433-6b670f80-12bc-11eb-88ea-b36021a05a49.jpg)

**Comment by yuvalbl** [comment]
Agreed
text should be in a single line, when lowest number is on the right (for Hebrew, and vice versa for English)

![image](https://user-images.githubusercontent.com/11487010/97458848-c85d6800-1943-11eb-8276-bc2ce8e55b59.png)
