### ISSUE TITLE
 Infinite scrolling not work on news side bar[Bug]

### ISSUE THREAD

**Issue by danielsh28** [hasadna/anyway-newsflash-infographics#444]
When scrolling down the news sidebar the scroll event not fired.
After a quick examination, a redundant `<Box>` element need to be removed inside the `<SideBar>` element.
The situation now is that the scroll event is added to a HOC component `InfinitScroll` which is not trigger the event.

The sidebar should upload new news content when users reach the end of scrolling.

**Comment by yuvalbl** [comment]
infinite scroll should be invoke loading a new batch of items before reaching the bottom.
If measured in pixels - about 20-30 px before reaching the bottom
If measured in items - when the last item is visible

For instance, a new batch should be loaded in this case:

![image](https://user-images.githubusercontent.com/11487010/98134387-61056200-1ec7-11eb-89e6-df2c14e8763d.png)
