### ISSUE TITLE
[Bug] most severe accidents table is not displayed

### ISSUE THREAD

**Issue by yuvalbl** [hasadna/anyway-newsflash-infographics#454]
**Describe the bug**

**To Reproduce**
1. Go to https://anyway-newsflash-infographics.web.app/newsflash/54992
2. See error on "most severe accidents table" card

**Expected behavior**
Table should be displayed (even when `text` is undefined - see image)
**Screenshots**
![image](https://user-images.githubusercontent.com/11487010/98134610-98740e80-1ec7-11eb-87d5-64ef55be9b3e.png)

**Environment**
Browser: Chrome
Environment: Staging / etc.

**Comment by almogbhl** [comment]
solved
