### ISSUE TITLE
[Bug] map is not displayed

### ISSUE THREAD

**Issue by yuvalbl** [hasadna/anyway-newsflash-infographics#462]
**Describe the bug**
our domain has changed
Our google maps keys should accept the following domains (ask @atalyaalon  for help):

https://anyway-infographics-staging.web.app
https://anyway-infographics.web.app
https://anyway-infographics-euro.web.app/

1. Go to https://anyway-infographics-staging.web.app/newsflash/56178
1. See error:

![image](https://user-images.githubusercontent.com/11487010/98833778-19428580-2447-11eb-9f5d-330b029b10cc.png)

**Comment by atalyaalon** [comment]
Solved
@almogbhl FYI
