### ISSUE TITLE
[Bug] BarWidget - text below bars overflow

### ISSUE THREAD

**Issue by yuvalbl** [hasadna/anyway-newsflash-infographics#480]
**To Reproduce**
1. Go to Bar widget
2. See bottom text

**Screenshots**
![image](https://user-images.githubusercontent.com/11487010/100935164-6c64a100-34f8-11eb-8ba0-c81f2c652a3a.png)

**Comment by adele-angel** [comment]
https://github.com/recharts/recharts/issues/961
