### ISSUE TITLE
[Refactor] Add text in the bottom of each widget

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway-newsflash-infographics#492]
You can find the text in the API in the following path: ["meta"]["dates_comment"]

<img width="645" alt="Screen Shot 2020-12-05 at 18 47 21" src="https://user-images.githubusercontent.com/20992625/101258303-53dbcd00-372a-11eb-9916-035699ae23ec.png">

**Comment by yuvalbl** [comment]
should be done along with #493
