### ISSUE TITLE
[Feat] most_severe_accidents_table

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway-newsflash-infographics#498]
**Is your feature request related to a problem? Please describe.**
Modify table as following:
1. Order accidents by date (descending)
2. Columns: 
- Replace "פצועים קשה" header to "קשה" and add column for light injured named "קל"
- Replace "הרוגים" to "הרוג"
3. Remove the red color from the table (no cells will be colored in red)

**screenshot**
<img width="540" alt="Screen Shot 2020-12-08 at 21 57 23" src="https://user-images.githubusercontent.com/20992625/101535106-cf46b400-39a0-11eb-954b-6b18255b0a75.png">

**Comment by atalyaalon** [comment]
@yuvalbl I corrected the description to order in descending order rather than ascending - FYI

**Comment by yuvalbl** [comment]
solved
