### ISSUE TITLE
Add "i" button for each widget showing information + methodology

### ISSUE THREAD

**Issue by galraij** [hasadna/anyway-newsflash-infographics#530]
Step 1:
Add the  [info icon](https://material.io/resources/icons/?icon=info&style=outline) (probably named `InfoOutlinedIcon`) and add a [tooltip support](https://material-ui.com/components/tooltips/)
Once completed - keep it hidden until step 2 can be completed
Keep in mind #526 is also working on this button row

Step 2 (Blocked):
Once info text will be served, we'll display it
Leave this issue open until we can connect it to meta data

![image](https://user-images.githubusercontent.com/11487010/103359067-d48ab080-4abf-11eb-99bf-70c3946b4434.png)

**Comment by galraij** [comment]
![Screenshot_23_12_2020__19_57](https://user-images.githubusercontent.com/3368312/103024836-46f80f80-4559-11eb-9172-7c1d86ce583b.png)

**Comment by yuvalbl** [comment]
@atalyaalon when do you estimate this would be ready?

**Comment by atalyaalon** [comment]
@yuvalbl we added mock information - it will be ready in API tomorrow (Thursday) evening

**Comment by atalyaalon** [comment]
Also - we'll add the real information soon - so please don't merge this button to production until real data is connected

**Comment by atalyaalon** [comment]
@yuvalbl @yoavpo the information is now in API under ["meta"]["information"]
Right now it's a placeholder - soon we'll have real data there
