### ISSUE TITLE
[Bug] newsflash feed - lazy load fetch the same items

### ISSUE THREAD

**Issue by yuvalbl** [hasadna/anyway-newsflash-infographics#540]
**Describe the bug**
newsflash feed - lazy load fetch the same items

IMPORTANT UPDATE:
API now supports pagination. instead of  "count" use "offset" and "limit"
see https://github.com/hasadna/anyway-newsflash-infographics/issues/540

**To Reproduce**
Scenario 1:
1. open network tab and use  filter `/api/news-flash`
2. Go to Homepage
3. See initial limit is 10
4. click on ynet - see request does not contain `limit` param
5. click on all - see request does not contain `limit` param

Scenario 1:
1. open network tab and use  filter `/api/news-flash`
2. Go to Homepage
3. See initial limit is 10
4. scroll newsflash feed down to the bottom- see nest request limit is 5
5. scroll newsflash feed down to the bottom again - each time limit add 5 to it's value

**Expected behavior**
* Lazy loading batch (limit) should be  constant (value of 100 is a good start)
* Pagination should be added to the URL (something like "start_item_index" param). should be discussed with @atalyaalon 

**Environment**
Browser: Chrome 
Environment:  Staging 

**Additional context**
See [API doc](https://docs.google.com/document/d/1Hv5ItvwM3z9nn95LjlsYHL-o18V8PgWrrQOKIPiPymU/edit)

**Comment by atalyaalon** [comment]
[Opened an issue in BE](https://github.com/hasadna/anyway/issues/1650)

**Comment by idosavion** [comment]
hi @atalyaalon  @yuvalbl @almogbhl,
I think an easy API for both BE and FE here will be to add two optional parameters to the query string:
    - `page`, which will be 1 by default
    - `count/per_page_count`, which will be 100 by default as Yuval suggested.
let me know if you agree so I can start implementing it on from BE side

**Comment by yuvalbl** [comment]
@idosavion
Fine by me

**Comment by atalyaalon** [comment]
@idosavion In addition to what @yuvalbl wrote, I suggest following best practices if there are ones. Besides that, seems good to me, you can start implementing.

**Comment by idosavion** [comment]
@yuvalbl, np, but let call the second param `limit` instead of `count`? will indicate that the query might include less items if `offset` is big enough

**Comment by idosavion** [comment]
https://github.com/hasadna/anyway/pull/1676

**Comment by atalyaalon** [comment]
@yuvalbl @almogbhl 
API is in production - you can use it :) - @idosavion  thank you so much!
Note - it's unrelated to this issue - but there is a small bag you encountered yesterday - of News Flashes that don't have road_segment but still appear in the API - we're working to solve this - [see this issue](https://github.com/hasadna/anyway/issues/1690).
