### ISSUE TITLE
[Feat] add label header varient

### ISSUE THREAD

**Issue by yuvalbl** [hasadna/anyway-newsflash-infographics#552]
Card Label Header style (HeaderVariant.Label) :
![image](https://user-images.githubusercontent.com/11487010/103779882-f5fa1800-503c-11eb-9585-a82e6d1ac09d.png)

Steps
1.in `CardHeader.tsx` add a new option to the main `switch`

```
switch (variant) {
    case HeaderVariant.Centered:
     //...
   case HeaderVariant.Label: 
   //  ==== Your code here === //
    case HeaderVariant.Logo:
     //...
```

2. Test new variant in cards to see it displayed properly 

Additional info:
background image already implemented for `HeaderVariant.Label`

Zeplin:
https://scene.zeplin.io/project/5f2ad1e8cc0681304b8f877a

**Comment by yoavpo** [comment]
What's the background color?
What's the text color?
How wide should the label be?
`CardHeader`'s `text` prop is showing empty on card using this variant like `head_on_collisions_comparison_percentage`

**Comment by yuvalbl** [comment]
header varient does not look like design

**Comment by eidan66** [comment]
> header varient does not look like design

I need the permissions to zeplin to get the design.

**Comment by eidan66** [comment]
I oped new PR -> #636 
Now it's look like this : 
![image](https://user-images.githubusercontent.com/41434778/113918612-52f79c80-97eb-11eb-8409-e70b4b64d4ee.png)
