### ISSUE TITLE
[Feat] Support localization using API lang variable

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway-newsflash-infographics#561]
**Is your feature request related to a problem? Please describe.**
Please call API with lang variable - currently supported lang=he and lang=en
Note: not all widgets are localized at the moment in API - it's WIP.
If a widget doesn't have an english translation, hebrew strings will appear by default.

**Additional context**
Example for API localized - [heberw](https://www.anyway.co.il/api/infographics-data?news_flash_id=63230&years_ago=5&lang=he) and [english](https://www.anyway.co.il/api/infographics-data?news_flash_id=63230&years_ago=5&lang=en)

**Comment by atalyaalon** [comment]
BTW @yuvalbl right now we see English string when website is on Hebrew, any idea why?

**Comment by yuvalbl** [comment]
Dunno. Can you specify steps to reconstruct?

**Comment by atalyaalon** [comment]
@yuvalbl made this priority 1 since strings in production are in English without this API lang variable

**Comment by yuvalbl** [comment]
Moved to milestone 0.3.0
