### ISSUE TITLE
[Feat] Update to the new injured_count_per_age_group widget

### ISSUE THREAD

**Issue by BarVolunteering** [hasadna/anyway-newsflash-infographics#564]
**Is your feature request related to a problem? Please describe.**
Update to the new injured_count_per_age_group widget in the backend server

**Describe the solution you'd like**
Update the FE code to be compatible 

**Additional context**
The new BE code is currently only dev branch and not in master branch or PROD.
More info is available at issue [#1645](https://github.com/hasadna/anyway/issues/1645) in anyway BE server project, Image:
![image](https://user-images.githubusercontent.com/58947331/104359621-8f7f6900-5518-11eb-9812-edd0d51fb165.png)

**Comment by BarVolunteering** [comment]
@atalyaalon

**Comment by yuvalbl** [comment]
@atalyaalon Let's discuss the design for this card

**Comment by BarVolunteering** [comment]
Example of a returned json:
``` json
{
      "name": "injured_count_per_age_group",
      "data": {
        "items": {
          "00-04": {
            "fatal": 1,
            "severe": 2
          },
          "05-09": {
            "fatal": 1,
            "severe": 4
          },
          "10-14": {
            "severe": 5
          },
          "15-19": {
            "fatal": 7,
            "severe": 17
          },
          "20-24": {
            "fatal": 6,
            "severe": 39
          },
          "25-34": {
            "fatal": 7,
            "severe": 35
          },
          "35-44": {
            "fatal": 11,
            "severe": 36
          },
          "45-54": {
            "fatal": 11,
            "severe": 29
          },
          "55-64": {
            "fatal": 11,
            "severe": 12
          },
          "unknown": {
            "fatal": 1,
            "severe": 6
          },
          "65+": {
            "fatal": 13,
            "severe": 21
          }
        },
        "text": {
          "title": "Injury severity per age group in מחלף קמה - צומת פלוגות"
        }
      },
      "meta": {
        "rank": 14
      }
    }
```

**Comment by yuvalbl** [comment]
@atalyaalon
If I remember correctly, "items" supposed to be an array, not an object

**Comment by atalyaalon** [comment]
@yuvalbl so at the time we decided it can be either an array or an object - see accident_count_by_severity widget

**Comment by atalyaalon** [comment]
Created a new issue [here](https://github.com/hasadna/anyway-newsflash-infographics/issues/827)
