### ISSUE TITLE
[Bug] head_on_collisions_comparison - 100% head on collisions

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway-newsflash-infographics#568]
**Describe the bug**
When the percentage of head on collisions is 100% - other accidents still appear

**Screenshots**
<img width="553" alt="Screen Shot 2020-12-25 at 11 08 46" src="https://user-images.githubusercontent.com/20992625/104746692-4c133d80-5758-11eb-974d-076cfd3666bf.png">

**Comment by atalyaalon** [comment]
@yuvalbl FYI

**Comment by yuvalbl** [comment]
@atalyaalon Please check-in staging
slice for "zero percent" is not displayed. we still need to remove the label for 0-percent + relocate the other lable
![image](https://user-images.githubusercontent.com/11487010/104815987-c9a28080-5820-11eb-8ecb-724ae66f910b.png)

**Comment by yuvalbl** [comment]
@atalyaalon I think that for 100% we should use a circle and a label in its center, nothing more

**Comment by atalyaalon** [comment]
@yuvalbl Sounds good, thanks

**Comment by yuvalbl** [comment]
Will be treated in #592
