### ISSUE TITLE
[Feat] Add vision_zero_2_plus_1 infographics

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway-newsflash-infographics#577]
**Is your feature request related to a problem? Please describe.**
vision_zero_2_plus_1 Widget

**Describe the solution you'd like**
Add Widget to FE when Widget vision_zero_2_plus_1 appears in API.
Design: https://github.com/hasadna/anyway-newsflash-infographics/issues/609
Also - please remove the placeholder of widget called vision_zero from FE - we want to delete it from the API

**Additional context**
BackEnd issue for adding this API: https://github.com/hasadna/anyway/pull/1692

**Comment by yuvalbl** [comment]
Waiting for final design
