### ISSUE TITLE
[Bug] accident_count_by_severity - breaks on LTR 

### ISSUE THREAD

**Issue by yuvalbl** [hasadna/anyway-newsflash-infographics#590]
**Describe the bug**
accident_count_by_severity - when changing language to English,
the card content is close to the left

Expected:
Card content should be centered for all languages

![image](https://user-images.githubusercontent.com/11487010/107555571-fd828300-6bdf-11eb-8208-7f579ace7578.png)

**Comment by YaronAvraham93** [comment]
Someone has already solved this problem

**Comment by yuvalbl** [comment]
Could not reconstruct
