### ISSUE TITLE
[Refactor] head_on_collisions - labels

### ISSUE THREAD

**Issue by yuvalbl** [hasadna/anyway-newsflash-infographics#592]
1. Pie chart labels are currently supplied by the server
Since these are static values, they should be treated as any static text (make sure it works with i18n)
![image](https://user-images.githubusercontent.com/11487010/107563998-6e2e9d00-6bea-11eb-83ef-7ece215563a4.png)

2. When one label have value of "0" it should not be displayed
In addition, the other label should be centered in such a case (see #568)
![image](https://user-images.githubusercontent.com/11487010/107564246-d0879d80-6bea-11eb-87ef-53fa93d60e86.png)

This issue includes treatment for #568
both can be closed once this issue is completed

**Comment by 9Syncopation** [comment]
the first issue - regarding the duplicated text label was not observed
