### ISSUE TITLE
[Bug] Severe Accidents does not show in accident_count_by_severity widget

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway-newsflash-infographics#595]
**Describe the bug**
API contains severe accidents.

**To Reproduce**
See the following link: https://anyway-infographics-staging.web.app/newsflash/67860
(Make sure you're not looking at the mock data)

**Expected behavior**
Show severe accidents count 

**Screenshots**
![Screen Shot 2021-02-17 at 20 46 35](https://user-images.githubusercontent.com/20992625/108252390-3e8b1200-7161-11eb-94f0-d6cf1a14156a.png)

**Environment**
Browser: Chrome 
Environment: Local / Staging / etc.

**Additional context**

**Comment by yuvalbl** [comment]
solved
