### ISSUE TITLE
[Bug] Default language is English rather than Hebrew

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway-newsflash-infographics#596]
**Describe the bug**
When using Staging/Production, default language is English:
https://anyway-infographics-staging.web.app/

**Expected behavior**
Make sure default language is Hebrew

**Comment by yuvalbl** [comment]
@atalyaalon 
Can't reconstruct

**Comment by atalyaalon** [comment]
@yuvalbl take a look at the table in this link: https://anyway-infographics-staging.web.app/

**Comment by atalyaalon** [comment]
![Uploading Screen Shot 2021-02-24 at 18.38.34.png…]()

**Comment by atalyaalon** [comment]
@yuvalbl I see that the lang param is not sent in query?

**Comment by yuvalbl** [comment]
It was not implemented yet, it is currently defined as low priority
However, I see  hebrew as the default  when I click the link

**Comment by atalyaalon** [comment]
<img width="1072" alt="Screen Shot 2021-02-24 at 18 38 34" src="https://user-images.githubusercontent.com/20992625/109035238-1c4d4300-76d1-11eb-8f66-e9722449633b.png">

@yuvalbl  Weird - that's what I see... table with english content (For example - Collision of front to rear-end)
perhaps we should move the lang feature into a higher priority

**Comment by yuvalbl** [comment]
should be solved by #561
