### ISSUE TITLE
[Feat] News Flash Date Format 

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway-newsflash-infographics#597]
**Is your feature request related to a problem? Please describe.**
Modify format based on the news flash language:
Hebrew / Arabic - dd/mm/yyyy
English - mm/dd/yyyy

Nowadays format is mm/dd/yyyy - not friendly for Hebrew / Arabic speakers.

UPDATE:

- this format should be used for all dates in the app (card footer, newsflash, tables etc)
- day and month should always be with 2 digits (example: 08/02/2020)

**Comment by noa-ui** [comment]
#739
