### ISSUE TITLE
[Feat] Create a generic design for Stacked bar chart infographic

### ISSUE THREAD

**Issue by galraij** [hasadna/anyway-newsflash-infographics#601]
<img width="899" alt="כרטיסיות_חדשות_לעיצוב_-_סדר_עדיפויות_pdf" src="https://user-images.githubusercontent.com/3368312/109391450-cde1b380-791f-11eb-92e5-f3c51edf5585.png">

**Comment by Mr-DannyDin** [comment]
![Stacked-Bar-Chart](https://user-images.githubusercontent.com/79767188/109503101-82a3de00-7aa2-11eb-9c23-6208ae805d65.jpg)
Hello again!
Here's our take on the generic stacked bar chart slide.

**Comment by galraij** [comment]
@Mr-DannyDin as in other cases it would be great to have the place holder for the number to include at the top of the bar.
