### ISSUE TITLE
[Feat] Design Vision Zero 2+1 Solution

### ISSUE THREAD

**Issue by galraij** [hasadna/anyway-newsflash-infographics#609]
![כרטיסיות_למוקאפ_דוח_עיתונאים_key](https://user-images.githubusercontent.com/3368312/109394331-22d8f600-792f-11eb-84c5-01b0229cf3e0.png)

the texts:

כביש 2+1 על פי ״חזון אפס״ למניעת תאונות חזיתיות בכבישים בין עירוניים

כביש בן שלושה מסלולים, שמורכב משני מסלולים בכיוון אחד ומסלול בודד בכיוון הנגדי, המתחלפים מדי מספר קילומטרים.

מביא לירידה של כ-90% בכמות ההרוגים.

מעבר משני מסלולים לאחד ממתנת את מהירות הנסיעה

גדר הפרדה המונעת תאונות חזיתיות

ניתן ליישם בכבישים דו מסלוליים קיימים

**Comment by Mr-DannyDin** [comment]
![visionZERO_road](https://user-images.githubusercontent.com/79767188/109434122-61001380-7a1c-11eb-8496-7f70a59e8886.jpg)
Fresh out of the oven guys!
Our suggestion for Vision Zero's 1+2 road.
We found a tiny error in the text and fixed it (הנכון: המעבר ממתן).
Q: Do we have a vector version of the Vision Zero logo? Will surely come in handy.

**Comment by galraij** [comment]
@Mr-DannyDin Amazing work!

About the logo - I couldn't find it.

Actually, this logo is made by one of the projects like us, and is not really the original logo of the foundation. I will do a little research of the appropriate logo or we will create a simple and similar one (maybe without the little icons at the top that are hardly seen)

**Comment by atalyaalon** [comment]
@galraij @Mr-DannyDin are we missing anything for this design? Or is it final?

**Comment by atalyaalon** [comment]
@galraij can we close this one?
