### ISSUE TITLE
[Bug] App crashes in dev environment - HeatMap 

### ISSUE THREAD

**Issue by danielsh28** [hasadna/anyway-newsflash-infographics#620]
![image](https://user-images.githubusercontent.com/28825057/111183717-e2c57480-85b8-11eb-9ba9-0f10a2989f9b.png)

**Comment by yuvalbl** [comment]
Error: `Cannot read property 'leafletElement' of null`

This reconstruct it (see console):
https://anyway-infographics-staging.web.app/newsflash/73375

**Comment by danielsh28** [comment]
will be solved in [this issue](https://github.com/hasadna/anyway-newsflash-infographics/issues/653)
