### ISSUE TITLE
[Feat] Allow to choose a point on the map (instead of a newsflash)

### ISSUE THREAD

**Issue by galraij** [hasadna/anyway-newsflash-infographics#678]
Story1
User click on search button, search in map input, receive section, confirm and receive widgets.

Story2
User click on search button, search on the map, receive section, confirm and receive widgets.

Story3
User click on search button and cancel.

Design
https://www.figma.com/file/AJb0s5LH7Vpo9MqciMM0rY/Anyway?node-id=0%3A1

* Design a location picker component  - #687 
* add 'search' button to app bar - #714
* add an indicator to news flash feed #717
* create map dialog #719
* create outlined button atom #721

**Comment by yuvalbl** [comment]
@atalyaalon API spec required

**Comment by grandcohen** [comment]
Figma:
https://www.figma.com/file/AJb0s5LH7Vpo9MqciMM0rY/Anyway?node-id=0%3A1
