### ISSUE TITLE
[Bug] page flickers on scroll changes

### ISSUE THREAD

**Issue by yuvalbl** [hasadna/anyway-newsflash-infographics#706]
![anyway-flickers](https://user-images.githubusercontent.com/11487010/125633312-aedbb725-e798-4154-b24b-79fd3ad0020a.gif)
**Describe the bug**

**To Reproduce**
1. Go to https://media.anyway.co.il
2. See app flickers on initial load
3. click on "show more"
4. See app flickers on collapse / expand

**Expected behavior**
no flickering
no scroll for the main view (in fact, we should prevent it - see below)

**Environment**
Browser: Chrome
Environment: Production

**Additional context**
Main view should prevent scrolling - scroll should appear on main-content area (widgets) and feed only
My guess is this issue can be solved simply by `scroll:hidden` on the main view

UPDATE:
To prevent future regression issues, we should have a better understanding of the cause of this bug.
please research this image and find the responsible commit

**Comment by MashaPav** [comment]
@yuvalbl it happens because of:

::-webkit-scrollbar in index.css

Can we just remove this component? I don't see it affecting anything else

**Comment by MashaPav** [comment]
was added in this commit:
https://github.com/hasadna/anyway-newsflash-infographics/pull/122/commits/1aaab3c32eca64fa4843026e82417ed2df728995

**Comment by MashaPav** [comment]
Handled in https://github.com/hasadna/anyway-newsflash-infographics/pull/713
