### ISSUE TITLE
[Feat] create map dialog 

### ISSUE THREAD

**Issue by SejoB** [hasadna/anyway-newsflash-infographics#719]
![image](https://user-images.githubusercontent.com/39242962/126535594-988ae2a1-7e10-4aab-9279-0f0ba0059290.png)
- create molecule MapDialog
- dialog should include
   - header 
   - main section
   - footer with buttons
   - section that display chosen section 
- make sure to add translation for : header, chosen section, buttons
* Note: NO need to add the map
#678 
waiting for #721

**Comment by daniel-ilan** [comment]
I have two questions about this component:

1. The font of the header and the bolder text at the bottom are bolder then we have (we need to import a bolder font). I think it's made with 'Rubik - Black' which we don't import yet. Please let me know how to continue.
2. This is waiting for the outline button (#721 )


Please see this commit and let me know if there is anything else should be done before opening a PR - https://github.com/hasadna/anyway-newsflash-infographics/commit/2154695bbb66f5bd6d56cba0d7f164f848ade68e#diff-1286fc19991f2c3010c005b2905aa46cf59bf8a00583e2c3890c7cc166affa88
