### ISSUE TITLE
[Feat] URL per newsflash

### ISSUE THREAD

**Issue by mimafogeus2** [hasadna/anyway-newsflash-infographics#72]
**Is your feature request related to a problem? Please describe.**
Each newsflash should have its own URL that could be linked to, sent, bookmarked...

**Describe the solution you'd like**
Our main page should have a path with a variable (/:id) that represents the newsflash.
When the page loads or the path changes, the page will launch a request to fetch the relevant newsflash's data, then display it.
This will replace the current behavior of loading the data in an onClick callback.

**Additional context**
This should work with the implementation for issue #71.

**Comment by yuvalbl** [comment]
solved by #96
