### ISSUE TITLE
[Feat] User Management screen

### ISSUE THREAD

**Issue by yuvalbl** [hasadna/anyway-newsflash-infographics#724]
Manage organization-theme assignment per user

Steps:
1. Create Admin Modal (see below)
1. TBD (Waiting for API) - @atalyaalon  please provide spec

Step 1: Admin modal
On the top bar, next to "log out" add "Admin" button
![image](https://user-images.githubusercontent.com/11487010/129066667-5f861136-825d-4317-9be4-436654b69a03.png)

When clicked, a modal should be opened with the following UI:
![image](https://user-images.githubusercontent.com/11487010/129067984-ade5f19f-f9b5-4204-a647-3b264d836901.png)

- When clicking "edit" the "organization" text should change to a dropdown with the list of organizations, and the button should be replaced with 2 buttons:  "save" and "cancel"

UPDATES:
* User can be assigned for ONLY ONE organization 
* Currently there is 1 possible role: Admin, which will be user to allow editing users (using this admin panel)
If user has no role - it can still be assigned to an organization (and get organization theme and widgets)

**Comment by yuvalbl** [comment]
requirements:

API
- get all users
- change the organization of user

DB
- Set @atalyaalon @danielsh28  and @yuvalbl  as Admins
- Add "organizations" table
- Add "organization" column on "users" table

**Comment by atalyaalon** [comment]
DB: @atalyaalon @danielsh28 @yuvalbl and @BarVolunteering  are Admins

**Comment by atalyaalon** [comment]
Current documentation: https://github.com/hasadna/anyway/blob/master/docs/USERAPI.md

@BarVolunteering can elaborate more.

**Comment by BarVolunteering** [comment]
The current documentation are in: https://github.com/hasadna/anyway/blob/master/docs/USERAPI.md
Except for 4 APIs that are documented in Swagger (not merged to Master), which are:
**POST /user/add_organization**
that get a json like `{"name": "Anyway"}` and return HTTP OK

**POST /user/remove_user_from_org**
that get a json like `{"email": "ron@gmail.com", "org": "Anyway"}` and return HTTP OK

**POST /user/add_user_to_org**
that get a json like `{"email": "ron@gmail.com", "org": "Anyway"}` and return HTTP OK

**GET /user/get_organization_list**
return a list of organizations in DB

**Comment by danielsh28** [comment]
The table represents one organization per user, and according to the description in  https://github.com/hasadna/anyway-newsflash-infographics/issues/724#issue-954900165 we are needed to replace the current organization using a select box.
 
The current API implementation talks about a **list** of organizations and the functionality is **to add** organization to the user list of organizations instead of setting a new one.

We need to decide the implementation for UI and API a this. do we want a user to be able to obtain a list of org or do we need to set a new organization to use instead? @atalyaalon @BarVolunteering  @yuvalbl

**Comment by BarVolunteering** [comment]
@MichalOren will discuss with @galraij about what to do

**Comment by BarVolunteering** [comment]
@danielsh28 User can be in only one organization.
What i am thinking to do is to leave the API as is, and add a check in `/user/add_user_to_org` if the user is already a member in a another organization if yes then return 400 Bad Request

**Comment by yuvalbl** [comment]
@BarVolunteering see UPDATES section on the original messages

**Comment by BarVolunteering** [comment]
@yuvalbl Yes that is correct
