### ISSUE TITLE
[Doc] Edit CICD And Environments Section in README.md

### ISSUE THREAD

**Issue by MashaPav** [hasadna/anyway-newsflash-infographics#726]
Edit numbers 3 and 4 in https://github.com/hasadna/anyway-newsflash-infographics#cicd-and-environments to the below:

3. deploy-master: continuous deployment of master branch to Production Environment:
 -  https://anyway-infographics.web.app/
 -  https://media.anyway.co.il/
 
4. **[Deprecated]** deploy-demo: continuous deployment of demo branch to Demo Environment - https://anyway-infographics-demo.web.app/

**Comment by yuvalbl** [comment]
solve by #727
