### ISSUE TITLE
[Bug] Widget vision_zero_2_plus_1 does not appear in FE

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway-newsflash-infographics#746]
**Describe the bug**
See an [example here](https://media.anyway.co.il/newsflash/82212)
[Infographics API for this news flash](www.anyway.co.il/api/infographics-data?news_flash_id=82212&years_ago=5&lang=he) has the vision_zero_2_plus_1 widget, but the infographics does not appear

[Widget design is here](https://github.com/hasadna/anyway-newsflash-infographics/issues/609)

**Environment**
Browser: Chrome 
Environment: Both production and staging

**Comment by atalyaalon** [comment]
@SejoB can we add it to milestone 0.8.0?

**Comment by yuvalbl** [comment]
@atalyaalon 
yes

**Comment by SejoB** [comment]
@atalyaalon 
Hi, I fix this issue, but need fixes in backend
Data doesn't come in right format
![image](https://user-images.githubusercontent.com/39242962/129938894-0fac4535-a157-42e8-ad5b-8e207ecf9fd6.png)
Have to be;
 items: {
    image_src: string;
  }[];

**Comment by SejoB** [comment]
FE part done by #750

**Comment by atalyaalon** [comment]
@SejoB as discussed this is the [BE API](https://github.com/hasadna/anyway/pull/1879/files)
Please adjust.
