### ISSUE TITLE
[Feat] Add Absolute Import Rule

### ISSUE THREAD

**Issue by MashaPav** [hasadna/anyway-newsflash-infographics#766]
There are many places where imports are implemented as:

import { IPoint } from '../../models/Point';

We should implement a rule that would implement all imports as for example: 

import { IPoint } from 'models/Point';

**Comment by MashaPav** [comment]
If added as ESLint rule it might impact all the existing imports so be careful, and apply changes to existing imports if needed.

**Comment by MashaPav** [comment]
@yuvalbl @SejoB there is already a rule added via /anyway-newsflash-infographics/tsconfig.json from global imports inside 'src' so all the new global imports should be working from under 'src', but I didn't find a way to change the relative imports retroactively except manually. Are you familiar with something automatic? 

Related docs https://create-react-app.dev/docs/importing-a-component/#absolute-imports

**Comment by yuvalbl** [comment]
solved by #831
