### ISSUE TITLE
[Bug] accident_count_by_severity Widget is not present

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway-newsflash-infographics#771]
UPDATE: 
After backend changes - widget is presented, but in some cases -  still seeing 0 instead of "fatal" section. 
see: https://anyway-infographics-staging.web.app/newsflash/95432

**Describe the bug**
The above widget is not present [for the following news flash](https://media.anyway.co.il/newsflash/89100)
Even though [the widget does appear in API](https://www.anyway.co.il/api/infographics-data?lang=he&news_flash_id=89100&years_ago=5)

**Expected behavior**
The widget should appear

**Environment**
Browser: Chrome
Environment: both Staging and Production.

**Comment by yuvalbl** [comment]
This is accident_count_by_severity widget:
![image](https://user-images.githubusercontent.com/11487010/135294772-01fe7a8d-4fed-4ec7-9fc7-e4b7e28d19bf.png)

**Comment by atalyaalon** [comment]
Regarding this - it might be an BE API problem - I see there are no fatal accidents hence there is no entry in json for that category. Do you want us to add an entry when the number is 0? Or do you want to handle it in FE?

**Comment by atalyaalon** [comment]
I think this should solve it - https://github.com/hasadna/anyway/issues/1967
If not I will repoen

**Comment by atalyaalon** [comment]
@yuvalbl I thougt the above fix will solve it - and it did partially - however take a look at the dangling zero in the infographics:

link: https://media.anyway.co.il/newsflash/91527

Screenshot: 
![Screen Shot 2021-10-08 at 23 57 31](https://user-images.githubusercontent.com/20992625/136624105-c2f40417-eb4f-4df2-8dd3-f476334bb6a2.png)
