### ISSUE TITLE
[Bug] Typography component always shows as bold text

### ISSUE THREAD

**Issue by daniel-ilan** [hasadna/anyway-newsflash-infographics#773]
**Describe the bug**
Passing "bold" prop to Typography component doesn't affect the text and the default is bold (700)

**To Reproduce**
1. Go to any component that uses Typography
2. Make sure that it doesn't receive "bold" as prop
3. see that the text is still bold (font-wheight: 700)

**Expected behavior**
The text shouldn't be bold

The issue is that the useBold function receives an object holding the bold prop and is checking that object is always true

**Comment by chenmu10** [comment]
fixed via #775
