### ISSUE TITLE
New version of news-flash API

### ISSUE THREAD

**Issue by afedj** [hasadna/anyway-newsflash-infographics#774]
A new version of the news-flash API is available at: 
    https://www.anyway.co.il/api/news-flash-v2

### New capabilities

1. Support for filtering by street resolution (previously only interurban road was supported).
2. Filtering by multiple resolutions. 
3. Filtering by multiple sources (previously could only filter by a single source per request). 

### How to use

The API remains the same aside from the following changes:

1. **interurban_only** and **road_segment** query parameters are deprecated. 
In order to filter by resolution a new query parameter is introduced: **resolution**.
To filter by resolution use the following format: `resolution=<resolution1>&resolution=<resolution2>...` in the query string, e.g: 
https://www.anyway.co.il/api/news-flash-v2?resolution=suburban_road&resolution=street

     Currently the following 2 resolutions are supported: **suburban_road** (just a new name for interurban) and **street**.
     Filtering by resolution will only return results for which the relevant resolution information is available,
     hebrew street name for street resolution and road segment for suburban_road resolution.

2. Similarly for filtering by multiple sources use the `source=<source1>&source=<source2>...` format.

**Comment by afedj** [comment]
@yuvalbl

**Comment by yuvalbl** [comment]
@afedj 
A standard way to support API versioning would be `/API/VERSION/ENDPOINT`
like:
```
https://www.anyway.co.il/api/v1/...
https://www.anyway.co.il/api/v2/...
```
A better option is to use latest version as default, while keep other with version in the URL. like:
```
https://www.anyway.co.il/api/v1/...
https://www.anyway.co.il/api/...   //  this is version 2, which is currently the latest
```

**Comment by yuvalbl** [comment]
No versioning required - juts front-to-back collaboration
