### ISSUE TITLE
[Feat] Update generic bar chart components according to new design

### ISSUE THREAD

**Issue by yuvalbl** [hasadna/anyway-newsflash-infographics#779]
This feature contains 3 aspects

- Standard bar chart
- Stacked bar chart
- shared component

Standard bar chart - design is TBD
component: BarChartView

[Stacked bar chart](https://drive.google.com/file/d/17ne72PQBUtx9GwGTE13IsZNdgVjC6geY/view)
component: StackedBarChartView
![image](https://user-images.githubusercontent.com/11487010/135342162-17842c0a-6655-4cba-beec-53ea39f67eec.png)

 shared component
 some logic and component are shared for both type of charts, especially:

- solution for a chase when there are [small number of bars](https://drive.google.com/drive/folders/1bbq-jaiYqmpVReUspN2kajXutPT-OyBr)
![image](https://user-images.githubusercontent.com/11487010/135342514-aa2f689c-0e1b-47ec-ad1c-60b155aa551f.png)
- bar style (shadow like)
![image](https://user-images.githubusercontent.com/11487010/135342654-e81fa2a6-5f06-4cf1-910b-df2e03d09902.png)
![image](https://user-images.githubusercontent.com/11487010/135342692-192dd9e7-7935-4780-86f7-94921c26a105.png)

See which element can be extracted externally (can be a component, contestants etc)

Resources
[Drop shadow](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/drop-shadow()) can be used to achieve shadow effect (even for svg elements)
Round bar edges can be achieved by the Bar [radius property](https://stackoverflow.com/questions/55285570/creating-a-rechart-barchart-with-rounded-edges)

**Comment by chenmu10** [comment]
changes needed in json:
- Are the values in percentage? (or general prefix/postfix)
- how many bars in group? (1-X)
- isStacked?


**Issues**:
- labels in bars - dynamic positioning issue.
- shadow in stacked chart overlapping bars.
- hide if bar value is 0.
- need to test on real stacked data.
- tooltip design (can be postpone)
- change labels/names to objects
- general issue found: unnecessary loading the component for every widget - need to add keys.
**How it currently looks**:

1 bar:
![image](https://user-images.githubusercontent.com/13830519/141162620-98be1922-dca0-434e-b012-7e60a3418655.png)

2 bars:
![image](https://user-images.githubusercontent.com/13830519/141162242-cd0f871c-b6fe-4aca-bee0-b2c1a6f51e90.png)

3 bars - stacked:
![image](https://user-images.githubusercontent.com/13830519/141162411-d65004ae-2240-453b-88c5-f922ab9fa021.png)

**Comment by chenmu10** [comment]
Regarding json, can we change the format from:
```json
"name": "accident_count_by_accident_year",
      "data": {
        "items": {
          "1": { "2017": 1, "2018": 3, "2019": 1, "2021": 1, "2020": 0 },
          "2": { "2017": 5, "2018": 3, "2019": 6, "2020": 5, "2021": 5 },
          "3": { "2017": 55, "2018": 50, "2019": 68, "2020": 47, "2021": 39 }
        },
        "text": {
          "title": "\u05de\u05e1\u05e4\u05e8 \u05ea\u05d0\u05d5\u05e0\u05d5\u05ea \u05dc\u05e4\u05d9 \u05e9\u05e0\u05d4, \u05de\u05d7\u05d5\u05dc\u05e7\u05d5\u05ea \u05dc\u05e4\u05d9 \u05d7\u05d5\u05de\u05e8\u05d4, \u05d1\u05de\u05e7\u05d8\u05e2 \u05de\u05d7\u05dc\u05e3 \u05dc\u05e7\u05d9\u05d9\u05d4 - \u05e6\u05d5\u05de\u05ea \u05e2\u05e8\u05d3",
          "labels": {
            "1": {
              "name": "fatal",
              "localized_name": "\u05e7\u05d8\u05dc\u05e0\u05d9\u05ea"
            },
            "2": { "name": "severe", "localized_name": "\u05e7\u05e9\u05d4" },
            "3": { "name": "light", "localized_name": "\u05e7\u05dc\u05d4" }
          }
        }
```
to:

```javascript
items  = [
    { 'year':2011, 'killed_injury_severity_count': 40, 'severe_injury_severity_count': 50, 'light_injury_severity_count': 70 },
    { 'year':2012,'killed_injury_severity_count': 6, 'severe_injury_severity_count': 2, 'light_injury_severity_count': 8 },
    { 'year':2013,'killed_injury_severity_count': 12, 'severe_injury_severity_count': 34, 'light_injury_severity_count': 67 },
    { 'year':2014,'killed_injury_severity_count': 36, 'severe_injury_severity_count': 152, 'light_injury_severity_count': 263 },
    { 'year':2015,'killed_injury_severity_count': 13, 'severe_injury_severity_count': 2, 'light_injury_severity_count': 3 },
    { 'year':2016,'killed_injury_severity_count': 7, 'severe_injury_severity_count': 7, 'light_injury_severity_count': 45 },
    { 'year':2017,'killed_injury_severity_count': 37, 'severe_injury_severity_count': 12, 'light_injury_severity_count': 23 },
  ]
```

**Comment by yuvalbl** [comment]
How about this?
```
"name": "accident_count_by_accident_year",
"data":  { 
       "items": [
          {
            "label_key": "2017"
            "series": [
              { "label_key":  "light", "value": 55},
              { "label_key":  "severe", "value": 5},
              { "label_key":  "fatal", "value": 1},
            ]
          },
          {
            "label_key": "2018"
            "series": [
              { "label_key":  "light", "value": 50},
              { "label_key":  "severe", "value": 3},
              { "label_key":  "fatal", "value": 3},
            ]
          }
        ]
        },
        "text": {
          "title": "widget title bla bla"
          "labels_map": {
            "light": "\u05e7\u05d8\u05dc\u05e0\u05d9\u05ea"
            "severe": "\u05e7\u05e9\u05d4"
            "light": "\u05e7\u05dc\u05d4"
          }
        }
}
```

**Comment by ziv17** [comment]
Hi,
1 - Just verifying, the value may also be a string that needs to be translated.
2 - In addition to the more verbose style
     `{ "label_key":  "light", "value": 55}`, 
   we may prefer a shorter style
     `{ "light": 55}`
3 - I suggest to specifically specify the number of depth levels we have in items, e.g.
```
{
    "name": "accident_count_by_accident_year",
    "data": {
        "items_depth": 2,
        "items": [
            {
                "vehicle type": "car",
                "series": [
                    {"light": 55},
                    {"severe": 5},
                    {"fatal": 0}
                ]
            },
        ]
    },
    "text": {
        "title": "widget title bla bla",
        "labels_map": {
            "light": "\u05e7\u05d8\u05dc\u05e0\u05d9\u05ea",
            "severe": "\u05e7\u05e9\u05d4",
            "fatal": "\u05e7\u05dc\u05d4",
            "year": 'שנה',
            "vehicle type": 'סוג רכב',
            "car": "מכונית פרטית"
        }
    }
}
```
and then single level will be
```
{
    "name": "accident_count_by_accident_year",
    "data": {
        "items_depth": 1,
        "items": [
              {"label_key": "light", "value": 55},
              {"label_key": "severe", "value": 5},
              {"label_key": "fatal", "value": 1},
         ]
}
```
What do you think?

**Comment by chenmu10** [comment]
1. for me it's easier not to extract data from keys (not `"vehicle type": "car"` but `"label_key": "car",` )
2. if we do `"series": [{"light": 55},{"severe": 5},{"fatal": 0}] `why not one object without  array` {"light": 55,"severe": 5,"fatal": 0}`? but again generally I prefer to have label_key separately. 
3. I also need the params:
```
 is_percentage: boolean
  is_stacked: boolean
```
3. the transform function is able to handle single/multiple bars with the `"series"` object. Is it important to split?
```
const transformedItems = items.map((item) => {
    const { label_key, series } = item;
    const result: stringNumObject = {};
    const label = label_key.toString();
    result[translatedYLabelName] = getTranslatedLabel(label); //   {'סוג רכב':'אופניים'}    {'שנה':'2017'}
    series.forEach((dataPoint) => {
      const { label_key, value } = dataPoint;
      const label = getTranslatedLabel(label_key);
      result[label] = Math.round(value); //   {'year':2017, 'percentage_segment':5 ...series}
    });
    return result;
  });
```

**Comment by yuvalbl** [comment]
After discussion (8 Dec), we agreed on this spec
https://github.com/hasadna/anyway-newsflash-infographics/issues/779#issuecomment-971718076

**Comment by yuvalbl** [comment]
@chenmu10 is working on this issue, to create 2 generic components:
1. single bar chart 
2. multi bar chart + stacked

closing #601
