### ISSUE TITLE
[Feat] Accidents Severity :: Color markers according to severity.

### ISSUE THREAD

**Issue by mimafogeus2** [hasadna/anyway-newsflash-infographics#79]
## Accidents severity widget markers should be colored according to severity.

Currently `most_severe_accidents` is not displayed.
This widget should show:
1. a map with locations (see `LocationMap` component)
2. each location should displayed as a marker with appropriate color:
קשה - אדום
בינוני - צהוב
קלה - כחול

**Comment by yuvalbl** [comment]
see WidgetTemplate switch case - this is where `most_severe_accidents` should be included
![image](https://user-images.githubusercontent.com/11487010/76458287-fefd6700-63e2-11ea-94bc-8a9695bd60cf.png)

**Comment by yuvalbl** [comment]
Data sample:

![image](https://user-images.githubusercontent.com/11487010/76458602-77642800-63e3-11ea-98d1-076a5a30e7ba.png)
