### ISSUE TITLE
[Feat] Bring back last_update in the bottom of the widgets

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway-newsflash-infographics#803]
**Is your feature request related to a problem? Please describe.**
We had a last update date in the bottom of the widget and removed it temporarily since the format was change to unix timestamp ([by FE request here](https://github.com/hasadna/anyway/issues/1902)) - please bring it back to the previous situation (it's under meta -> dates_comment - > last_update and it's in epoch timestamp

**Additional context**
עדכון אחרון ...
![most_severe_accidents_table](https://user-images.githubusercontent.com/20992625/138459833-13ad96c5-c2e3-4c71-88d4-39539bf16ea5.png)

**Comment by yuvalbl** [comment]
Let's use ISO standard:
```
2021-11-03T16:23:30.574Z
```

**Comment by yuvalbl** [comment]
@atalyaalon 
Please update `last_update` to use  ISO standard, example : `2021-11-03T16:23:30.574Z
`

**Comment by shaysw** [comment]
@atalyaalon @yuvalbl QQ: for dates which are purely dates, e.g., without time, the iso format function returns something like  "2021-07-31", are we cool with that? or do we want to add "2021-07-31T00:00:00.000Z"?

**Comment by shaysw** [comment]
after discussing with @atalyaalon , decided to update last_update TS, and do the "most_server..." in a different PR/issue

**Comment by Harduf-l** [comment]
@shaysw please let me know when you update the date format (I believe "2021-07-31" is absolutely fine).  I am responsible for displaying it.

**Comment by yuvalbl** [comment]
solved by #838
