### ISSUE TITLE
[Bug] map doesnt center

### ISSUE THREAD

**Issue by noa-ui** [hasadna/anyway-newsflash-infographics#809]
the map doesnt center to the relevant place

**Comment by noa-ui** [comment]
![Untitled-2](https://user-images.githubusercontent.com/64693838/142040653-0dbec237-3086-4505-8268-98ee3003009f.png)
![Untitled](https://user-images.githubusercontent.com/64693838/142040664-83c02dde-76d0-4f4f-a0af-bd36c58d985f.png)

**Comment by noa-ui** [comment]
newsFlashCollection > activeNewsFlash כנראה באג בבקאנד - המידע שנשלח ל
מכיל את המיקום הנכון (location) 
אבל עם lat, lon - לא נכון
![Untitled](https://user-images.githubusercontent.com/64693838/146426824-409085da-2f06-4511-a75c-0ea112c67a91.png)

**Comment by yuvalbl** [comment]
backend issue
