### ISSUE TITLE
[Bug] Gap in widget title - accident_count_by_severity 

### ISSUE THREAD

**Issue by MichalOren** [hasadna/anyway-newsflash-infographics#833]
**Describe the bug**
There is a undesired new gap in widget title - accident_count_by_severity
See attached file. To the right is a good view and to the left is an unnecessary space in the title.
It happend when user download  widget image.

**To Reproduce**
1. Go to Production env --> accident_count_by_severity widget
2. Click on the arrow to "download image" 
3. See gap in widget title

**Screenshots**
See attached file. To the right is a good view and to the left is an unnecessary space in the title.

**Environment**
Browser: Chrome (please verifay also at : Safari / Firefox / etc.)
Environment:  Staging & Production

**Additional context**
![Gap_problem](https://user-images.githubusercontent.com/61007501/147325616-77717eb2-c22b-4aac-b49f-ba6fdf6d4f6d.png)

**Comment by yuvalbl** [comment]
may be solved by #835
