### ISSUE TITLE
[Bug] gps location map flickering on choosing location with zoom

### ISSUE THREAD

**Issue by SejoB** [hasadna/anyway-newsflash-infographics#852]

**Comment by chenmu10** [comment]
original: [Bug] location picker - after click map should not zoom out https://github.com/hasadna/anyway-newsflash-infographics/issues/787

**Comment by danielsh28** [comment]
To Reproduce: 

Click on  **search** in the app's header

try to pin a location on the map.
**expected behavior:** 
the pin will be at the selected location
**actual  behavior:**
the map will re-rendered with no pin.
נקרו נקודת GPS
