### ISSUE TITLE
[Bug] 0 appears in widgets 

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway-newsflash-infographics#874]
**Describe the bug**
widgets: head_on_collisions_comparison and head_on_collisions_comparison_percentage

**To Reproduce**
https://media.anyway.co.il/newsflash/108276
https://anyway-infographics-staging.web.app/newsflash/108276

**Expected behavior**
remove 0 in text "במקטע ...."

**Screenshots**
![Screen Shot 2022-03-29 at 16 42 09](https://user-images.githubusercontent.com/20992625/160625206-bf8c3db9-7083-499c-9824-ec6863ddffca.png)

**Environment**
Browser: Chrome 
Environment: Staging AND Production

**Comment by shaked-hayek** [comment]
Doesn't duplicate
