### ISSUE TITLE
[Bug] float number appears in road number

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway-newsflash-infographics#876]
**Describe the bug**
Instead of road X, X.0 appears in production (for example, 25.0 instead of 25, etc)

**Screenshots**
![Screen Shot 2022-03-30 at 20 06 25](https://user-images.githubusercontent.com/20992625/160920234-d4e57cfe-745a-4a9f-83e0-cc395cb1f0d4.png)

**Environment**
Browser: Chrome 
Environment: Staging and production.

**Comment by Harduf-l** [comment]
@atalyaalon @danielsh28 
hi, I checked it. the header comes as a string from the backend in the newsFlashWidgetsMeta object, under "location_text" property. I believe it's better to change it in the backend, and make sure to build the string with an integer.

**Comment by atalyaalon** [comment]
@Harduf-l you are right. We're changing in the backend. Closing this one.
