### ISSUE TITLE
[Feat] Add Street Search

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway-newsflash-infographics#884]
See epic issue: https://github.com/hasadna/anyway-tasks/issues/3

**Comment by ziv17** [comment]
Hi @BrkCoder,
So one API that returns all yishuv_name values, and
Another that receives yishuv and returns all its streets?
Did I get it right?

**Comment by Harduf-l** [comment]
@ziv17 hi ziv, yes. you got it right. i will be working on the frontend. please let me know when api  is ready. thank you :)

**Comment by ziv17** [comment]
Hi @Harduf-l,
- `/api/city` returns all the cities
- `/api/streets?yishuv_symbol=154` returns all streets of yishuv
- The `/api/infographics-data` now receives also location parameters instead of news-flash, e.g.
    `/api/infographics-data?street1_hebrew=דרך ששת הימים&yishuv_name=רמת גן&years_ago=3&lang=en`
    `/api/infographics-data-by-location?yishuv_symbol=5000&street1=2426&years_ago=3&lang=he`
    `/api/infographics-data?road_segment_id=60008&years_ago=5&lang=he`
- All these are already in the `master` branch

**Comment by Harduf-l** [comment]
@ziv17 @danielsh28 
thank you ziv!
when i run the queries in my url browser, it works fine.
but inside the project i get the following error:

![Capture](https://user-images.githubusercontent.com/88275350/164378289-cbc8fa48-4152-4a8d-ae61-38079a4ff30b.JPG)

is it possible that my user doesn't have the right access? 
I do a regular axios request like that:

export const fetchCitiesList = async (): Promise<any> => {
  try {
    const getCitiesUrl = '/api/city';
    const response = await axios.get(getCitiesUrl);
    return response.data;
  } catch (error) {
    console.error(error);
  }
};

**Comment by ziv17** [comment]
Hi @Harduf-l, I think it worth to try it from your browser
