### ISSUE TITLE
[Bug] - Invalid title in production for widget: accident_count_by_severity

### ISSUE THREAD

**Issue by MichalOren** [hasadna/anyway-newsflash-infographics#891]
**Describe the bug**
For urban news flashes, the title of accident_count_by_severity widget, is missing the street name

**To Reproduce**
https://media.anyway.co.il/newsflash/109938

**Expected behavior**
The title shuold be: 
בשנים 2014 - 2021 ברחוב קהילת צפת בנתניה התרחשו 7 תאונות

**Screenshots**
![image](https://user-images.githubusercontent.com/61007501/164480751-22b29bbd-1a36-46f1-a20d-363488143d07.png)

**Environment**
Environment: Production & Staging

**Additional context**
additional exsamples
1. For example: https://media.anyway.co.il/newsflash/110879
2. Incorrect identification: https://media.anyway.co.il/newsflash/110882

**Comment by danielsh28** [comment]
hi @atalyaalon ,  can we add to widgets of `STREET` resolution   meta field of `road_segment_text`
 like the current behavior in  `SUB_URBAN_ROAD` widget? 
 the current behavior in `SUB_URBAN_ROAD`  : 
  
![Screen Shot 2022-05-18 at 15 15 22](https://user-images.githubusercontent.com/28825057/169037336-3b6a9a96-a98b-4602-9936-eb06edb59891.png)

the current behavior in `STREET` widgets : 
![Screen Shot 2022-05-18 at 15 15 10](https://user-images.githubusercontent.com/28825057/169037421-f2181567-aee8-48f1-8bb1-a47210fdf5c4.png)
