### ISSUE TITLE
[Bug] Change display order in accident_count_by_accident_year widget

### ISSUE THREAD

**Issue by MichalOren** [hasadna/anyway-newsflash-infographics#892]
**Describe the bug**
For accident_count_by_accident_year widget change display order Inside each bar:
Fatal accidents - bottom 
Severe accident - middle 
Light accidents - top

**To Reproduce**
https://anyway-infographics-staging.web.app/newsflash/110843

**Expected behavior**
Current order:
light accidents - bottom 
Severe accident - middle 
fatal accidents - top

Expected order:
Fatal accidents - bottom 
Severe accident - middle 
Light accidents - top

**Screenshots**
![image](https://user-images.githubusercontent.com/61007501/164489213-439d928c-f50b-426d-b6f9-015b1d979641.png)

**Environment**
Environment:  Staging

**Comment by liron93** [comment]
In addition to Michal's notes:
1. the number should be straight.
2. change the headline like the other infographics.

**Comment by danielsh28** [comment]
Hi @atalyaalon 
 can you please reverse the order of the array that is part of the `data.items` of the widget `accident_count_by_accident_year` list.
 the array  is highlighted  in the square  in the image below:
![order_bug](https://user-images.githubusercontent.com/28825057/167702689-fc4e0044-280a-4470-b850-ce0454dd02ab.png)

**Comment by BarVolunteering** [comment]
@danielsh28 The order is reversed
