### ISSUE TITLE
[Feat] : Update injured_count_by_severity - look  & feel

### ISSUE THREAD

**Issue by MichalOren** [hasadna/anyway-newsflash-infographics#901]
**Is your feature request related to a problem? Please describe.**
The look and feel display of widget injured_count_by_severity is too similar to accident_count_by_severity
Therefore a change is required.

**Describe the solution you'd like**
The new design required bold and larger text for the number of casualties (in red) and a description of the casualties (in gray)
![image](https://user-images.githubusercontent.com/61007501/171470242-fd799f2a-a7af-4c96-8bdd-3a4ad2ff305b.png)

**Comment by danielsh28** [comment]
Hi @MichalOren 
for your review
<img width="616" alt="Screen Shot 2022-07-20 at 20 10 16" src="https://user-images.githubusercontent.com/28825057/180042186-9f457268-8837-4836-b471-6fc7e64fdda0.png">

**Comment by MichalOren** [comment]
Hi @danielsh28 
looks like the wireframe above. That's grate.
Note, the 'Lamas logo' & 'last update' text should be included at the footer of the widget. kindly fix it.
