### ISSUE TITLE
[Feat] Add Or Yarok Logo to all widget when Or Yarok user is logged in

### ISSUE THREAD

**Issue by galraij** [hasadna/anyway-newsflash-infographics#913]
As part of our personalization feature, when someone from a specific organization (that partners with us) is logged in, the widgets will contain its logo on it instead of the Lamas logo. First organization will be Or Yarok.

<img width="558" alt="Screen Shot 2022-08-03 at 15 52" src="https://user-images.githubusercontent.com/3368312/182616576-2844aa5b-409c-42db-845a-3476974e6da1.png">

**Comment by galraij** [comment]
![oryarok](https://user-images.githubusercontent.com/3368312/182618195-a2f517ac-b799-4ec5-a322-b7331ff7f3b7.png)

**Comment by MichalOren** [comment]
Hi 
when user log in you should please use **get user info** api
https://github.com/hasadna/anyway/blob/dev/docs/USERAPI.md#get-user-info
to verify OR YAROK ID
